# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - devel
  paths:
    exclude:
    - docs/README.md
    - README.md

pool:
  name: 'default'

steps:
- script: |
    echo Generate docker image from Dockerfile.devel
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-latest -f Dockerfile.devel .
    echo Generate docker image from Dockerfile.devel-gpu
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-gpu-latest -f Dockerfile.devel-gpu .
    echo Generate docker image from Dockerfile.prod-gpu
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(prodImageName)-gpu-latest -f Dockerfile.prod-gpu .
    echo Push images to DockerHub
    docker login -u $(dockerId) -p $(dockerPassword) $(telefonicaDockerHubDomain)
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-latest
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-gpu-latest
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(prodImageName)-gpu-latest
    echo Clean docker images from agent
    docker rmi $(docker images | grep gymnos | tr -s ' ' | cut -d ' ' -f 3)
  displayName: 'Generate docker images and push it to DockerHub'
