# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - devel
  paths:
    include:
    - docs/*
    exclude:
    - docs/README.md
    - README.md

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo $(dockerId)
    echo $(dockerPassword)
    echo $(imageName)
    echo Generate docker image from Dockerfile
    docker build -t kawatis/gymnos-devel:latest -f Dockerfile.devel .
    echo Show docker images
    docker images 
  displayName: 'Generate image from Dockerfile'

- script:
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push kawatis/gymnos-devel:latest
  displayName: 'Push container to DockerHub'
