# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - devel
  paths:
    exclude:
    - docs/README.md
    - README.md

pool:
  name: 'default'

steps:
- script: |
    DATE=$(date +%Y-%m-%d-%H-%M-%S)
    echo Generate docker image from Dockerfile.devel
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-$DATE -f Dockerfile.devel .
    echo Generate docker image from Dockerfile.devel-gpu
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-gpu-$DATE -f Dockerfile.devel-gpu .
    echo Generate docker image from Dockerfile.prod-gpu
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(prodImageName)-gpu-$DATE -f Dockerfile.prod-gpu .
    echo Push images to DockerHub
    docker login -u $(dockerId) -p $(dockerPassword) $(telefonicaDockerHubDomain)
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-$DATE
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(develImageName)-gpu-$DATE
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(prodImageName)-gpu-$DATE
  displayName: 'Generate docker images and push it to DockerHub'
