# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - devel
  paths:
    exclude:
    - docs/README.md
    - README.md

pool:
  name: 'default'

steps:
- script: |
    echo Generate docker images
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName)-latest -f Dockerfile .
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName)-gpu-latest -f Dockerfile.gpu .
    echo Push images to Telefonica artifactory
    docker login -u $(dockerId) -p $(dockerPassword) $(telefonicaDockerHubDomain)
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName)-latest
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName)-gpu-latest
    echo Clean docker images from agent
    docker rmi $(docker images | grep gymnos | tr -s ' ' | cut -d ' ' -f 3)
  displayName: 'Generate docker images and push it to DockerHub'
