# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - devel
  paths:
    exclude:
    - docs/README.md
    - README.md

pool:
  name: 'default'

steps:
- script: |
    echo Generate documentation
    sphinx-build -b html docs/source docs/build
  displayName: 'Documentation'
- script: |
    echo Generate docker images
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName) -f Dockerfile .
    docker build -t $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName):gpu-latest -f Dockerfile.gpu .
  displayName: 'Generate docker images'
- script: |
    echo Launching Functional Regression
    docker run $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName) -c experiments/boston_housing.json
    docker run $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName) -c experiments/mnist.json
  displayName: 'Test - Functional Regression'
- script: |
    echo Push images to Telefonica artifactory
    docker login -u $(dockerId) -p $(dockerPassword) $(telefonicaDockerHubDomain)
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName)
    docker push $(telefonicaDockerHubFullPath)/$(auraPrototypesRepo)/$(imageName):gpu-latest
  displayName: 'Push images to Telefonica artifactory'
- script: |
    echo Clean docker images from agent
    docker stop $(docker ps -a | grep gymnos | tr -s ' ' | cut -d ' ' -f 1)
    docker rm $(docker ps -a | grep gymnos | tr -s ' ' | cut -d ' ' -f 1)
    docker rmi $(docker images | grep gymnos | tr -s ' ' | cut -d ' ' -f 3)
  displayName: 'Agent cleaning'
