# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo Generate Dockerfile
    mv Dockerfile.devel Dockerfile
  displayName: 'Prepare Dockerfile'

- script: |
    echo Generate docker image from Dockerfile
    docker build -t $(dockerId)/$(imageName) .
  displayName: 'Generate image from Dockerfile'

- script:
    docker push $(dockerId)/$(imageName)
  displayName: 'Push container to DockerHub'
