FROM python:3.6.8

MAINTAINER pablo.lopezcoya@telefonica.com

WORKDIR /usr/src/app

RUN apt-get install libglib2.0-0 -y \
    && apt-get install libsm6 -y \
    && apt-get install libxrender-dev -y \
    && apt-get install libxext6 -y \
    && apt-get install curl -y

RUN pip install pipenv

COPY Pipfile* ./

RUN pipenv install

COPY . ./

VOLUME ["usr/src/app/trainings", "usr/src/app/datasets"]

RUN mkdir logs

ENTRYPOINT ["pipenv", "run", "python", "-m", "bin.scripts.gymnosd"]
