version: "2.4"

services:
    spark-master:
        image: bde2020/spark-master:2.4.0-hadoop2.7
        expose:
            - 7077
        environment:
            - INIT_DAEMON_STEP=setup_spark
        volumes:
            - "./data:/tmp/data"
    spark-worker-1:
        image: bde2020/spark-worker:2.4.0-hadoop2.7
        links:
          - spark-master
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
        volumes:
            - "./data:/tmp/data"
    gymnos:
        build: .
        links:
            - spark-master
        volumes:
            - "./data:/tmp/data"
            - "./cache:/usr/src/app/cache"
            - "./cache/keras:/root/.keras"
        depends_on:
            - spark-master
            - spark-worker-1
        env_file:
            - secrets.env
        entrypoint: python3 -m bin.scripts.gymnosd
