defaults:
    - trainer: ???
    - dataset: ???

test: false

show_config: true
show_dependencies: true

dependencies:
    install: false

mlflow:
    run_name: null
    experiment_name: Default
    log_trainer_params: true

