defaults:
    - trainer: ???
    - dataset: null
    - env: null

test: false

verbose: true

install: false

mlflow:
    disable: false
    run_name: null
    experiment_name: Default
    log_trainer_params: true
    log_dataset_params: true
    log_env_params: true
