name: Build docs for Github Pages

on: push

jobs:
  docs:
    name: Build docs
    runs-on: self-hosted
    container: python:3.7-slim
    steps:
      - name: Install rsync 📚
        run: apt-get update && apt-get install -y rsync git
      - name: Install requirements
        run: python -m pip install ".[docs]"
      - name: Build docs
        run: sphinx-build docs/source docs/build
      - name: Deploy to Github Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: docs/build
          clean: true
          clean-exclude: |
            .nojekyll
