name: Build docs for Github Pages

on: push

jobs:
    docs:
        name: Build docs
        runs-on: self-hosted
        steps:
            - name: Hello world
              run: echo "Hello world"
