name: Validate PEP8

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  flake8:
    runs-on: self-hosted
    container: python:3.7-slim
    steps:
      - uses: actions/checkout@v2
      - name: Install flake8
        run: python -m pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'flake8'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
