# @package trainer

_target_: gymnos.models.vision.image_classification.transfer_efficientnet.TransferEfficientNetTrainer
classes: ???
num_workers: 0
batch_size: 32
num_epochs: 20
gpus: -1
train_split: 0.6
val_split: 0.2
test_split: 0.2
